[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "developer"

[server]
port = 8502
headless = true
runOnSave = true
enableCORS = false

[global]
showWarningOnDirectExecution = false
